[package]
name = "first"
version = "0.1.0"
authors = ["yangdao <458424869@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#features = ["profiler"]
[dependencies]
seija = {path = "../../../seija",version = "0.1.0"} 